USER_ROLE_SUPER_USER = 1
USER_ROLE_CLIENT = 2
USER_ROLE_COURIER = 3
USER_ROLE_STAFF = 4
USER_ROLES = (
    (USER_ROLE_SUPER_USER, 'super admin'),
    (USER_ROLE_CLIENT, 'client'),
    (USER_ROLE_COURIER, 'courier'),
    (USER_ROLE_STAFF, 'staff'),
)