# Generated by Django 3.1.7 on 2021-05-07 09:00

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos', validators=[utils.validators.validate_extension, utils.validators.validate_size]),
        ),
    ]
