# Generated by Django 3.1.7 on 2021-05-14 14:11

import auth_.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0004_auto_20210514_0936'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', auth_.models.ClientManager()),
            ],
        ),
    ]
